# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f6632d4bad78b381f369ec0f8cc80432c93b2ebcf5718b8a5183d029c67bff55971f5783ecd770ea841a0102835bf42df187a1616a2336c020196e2a89e83d

test:
  secret_key_base: 480f0b72cce97d6d054d62e3d66543337859a92f06fe0aabe4c35e9c71190c1e29fd96ecda7870f5f7a49013585f58469c38698d3988da95da20b87ff8b9a51b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
